version: '3.9'

services:
  workout-app:
    build: 
      context: ./
      dockerfile: Dockerfile
    container_name: Workout-Api
    ports:
      - "8000:8000"

    depends_on:
      - workout_postgresql
    volumes:
      - ./workout-api:/workout-api
    # restart: always
    
  workout_postgresql:
    image: postgres:latest
    container_name: PostgreSQL
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workoutdb
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: PGadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: name@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    
    logging:
      driver: "none"

    depends_on:
      - workout_postgresql

  workout-frontend:
    build: 
        context: ./
        dockerfile: Dockerfile-frontend
    container_name: Workout-Frontend
    ports:
      - "5173:5173"

    volumes:
      - ./workout-frontend:/workout-frontend
    
    # restart: always
